[package]
name = "kakaotalk-adblock-win32"
version = "0.1.1"
authors = ["Hyunkoo Kang <cyluss@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.19"
native-windows-derive = "1.0.3"
native-windows-gui = "1.0.10"
winapi = "0.3.9"
